# Generated by Django 5.2.7 on 2026-09-05 09:54

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0063_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=50)),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or direct video URL', max_length=500, null=True)),
                ('video_file', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='custom_videos/')),
                ('poster_image', models.ImageField(blank=True, help_text='Preview image shown before video plays', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='video_posters/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('autoplay', models.BooleanField(default=False)),
                ('loop', models.BooleanField(default=False)),
                ('muted', models.BooleanField(default=True)),
                ('controls', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_name', models.CharField(default='home', max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_customizations', to='builder.publishedpage')),
            ],
            options={
                'unique_together': {('page', 'element_id', 'page_name')},
            },
        ),
    ]
