# Generated by Django 5.2.7 on 2026-09-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0064_videocustomization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocustomization',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Preview image shown before video plays', null=True, upload_to='video_posters/'),
        ),
        migrations.AlterField(
            model_name='videocustomization',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='custom_videos/'),
        ),
    ]
