# Generated by Django 5.2.7 on 2026-09-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0065_alter_videocustomization_poster_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocustomization',
            name='show_play_button',
            field=models.BooleanField(default=True, help_text='Show play button overlay on video'),
        ),
    ]
