# Generated by Django 5.1.4 on 2026-09-12 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0066_videocustomization_show_play_button'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAvailabilityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_available', models.BooleanField()),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Domain Availability Cache',
                'verbose_name_plural': 'Domain Availability Cache',
                'indexes': [models.Index(fields=['expires_at'], name='builder_dom_expires_0954f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=255)),
                ('tld', models.CharField(db_index=True, max_length=20)),
                ('is_free_tier', models.BooleanField(default=True, help_text="True if this request is covered by the user's plan (free domain benefit)")),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('purchasing', 'Purchasing'), ('purchased', 'Purchased'), ('configuring_dns', 'Configuring DNS'), ('active', 'Active'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending_review', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('registrar', models.CharField(blank=True, max_length=50)),
                ('registrar_order_id', models.CharField(blank=True, max_length=100)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_currency', models.CharField(default='USD', max_length=3)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('dns_configured', models.BooleanField(default=False)),
                ('dns_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, help_text='The store this domain is intended for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_requests', to='builder.publishedpage')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_domain_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain Request',
                'verbose_name_plural': 'Domain Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('registrar', models.CharField(default='namecheap', max_length=50)),
                ('purchase_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(db_index=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renewal_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_domains', to='builder.publishedpage')),
                ('source_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_domain', to='builder.domainrequest')),
            ],
            options={
                'verbose_name': 'Purchased Domain',
                'verbose_name_plural': 'Purchased Domains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='domainrequest',
            index=models.Index(fields=['user', 'status'], name='builder_dom_user_id_903694_idx'),
        ),
        migrations.AddIndex(
            model_name='domainrequest',
            index=models.Index(fields=['status', 'created_at'], name='builder_dom_status_f0872a_idx'),
        ),
        migrations.AddIndex(
            model_name='domainrequest',
            index=models.Index(fields=['domain_name'], name='builder_dom_domain__660c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseddomain',
            index=models.Index(fields=['expiry_date'], name='builder_pur_expiry__d7d90f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseddomain',
            index=models.Index(fields=['assigned_page'], name='builder_pur_assigne_cf08ec_idx'),
        ),
    ]
