# Generated by Django 5.1.4 on 2026-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0067_domainavailabilitycache_domainrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainrequest',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('purchasing', 'Processing'), ('purchased', 'Processed'), ('configuring_dns', 'Configuring DNS'), ('active', 'Active'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending_review', max_length=20),
        ),
    ]
