# Generated by Django 5.1.4 on 2026-09-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_paymenttransaction_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='free_domain_tlds',
            field=models.JSONField(blank=True, default=list, help_text="List of TLDs this plan can register for free. e.g. ['store'] or ['com', 'store']"),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_domains',
            field=models.IntegerField(default=0, help_text='Max custom domains per user account. 0 = no domains, -1 = unlimited'),
        ),
    ]
