# Generated by Django 5.1.4 on 2026-09-13 08:35

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_plan_free_domain_tlds_plan_max_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='webhook_secret',
            field=payments.models.EncryptedField(blank=True, max_length=1000, null=True),
        ),
    ]
