"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import base64
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# secret =  whsec_3b1c08b6e3f42fc10d84cc6e876dc8d2abbb7d861f1659cae87df42de59155e3


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xy!6d84+s1&&fxtzoaqp9ur79v(hc^wigt87vcbdysan^#(ism'
OPENROUTER_API_KEY=os.getenv('OPENROUTER_API_KEY', '')
OPENROUTER_MODELS = [
    # NVIDIA Models (Free)
    'nvidia/nemotron-3.5-lightning:free',
    'nvidia/nemotron-3-super-120b-a12b:free',
    'nvidia/nemotron-3-ultra-550b-a55b:free',
    'nvidia/nemotron-3-nano-30b-a3b:free',
    'nvidia/nemotron-nano-9b-v2:free',
    
    # Google Gemma Models (Free)
    'google/gemma-4-31b-it:free',
    'google/gemma-4-26b-a4b-it:free',
    
    # OpenAI OSS (Free)
    'openai/gpt-oss-20b:free',
    
    # Other Free Models
    'liquid/lfm-2.5-2.6b:free',
    'poolside/laguna-s-2.1:free',
    'poolside/laguna-xs-2.1:free',
    'cohere/north-mini-code:free',
    'openrouter/free',
    
    # Paid Models (fallback if you have credits)
    'openai/gpt-3.5-turbo',
    'openai/gpt-4o-mini',
    'openai/gpt-4o',
    'anthropic/claude-3-haiku',
    'mistralai/mistral-small-3.1-24b-instruct',
    'meta-llama/llama-3.1-70b-instruct',
]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Render.com domain and your custom domain
RENDER_DOMAIN = 'bynup-m6zc.onrender.com'
ALLOWED_HOSTS = [
    RENDER_DOMAIN,
    'localhost',
    '127.0.0.1',
    '.onrender.com',  # Allow all Render subdomains
    '*',  # Temporarily keep this if needed, but better to specify exact domains
]

# Allauth configuration to skip the intermediate page
SOCIALACCOUNT_LOGIN_ON_GET = True
# Auto-signup to skip additional forms
SOCIALACCOUNT_AUTO_SIGNUP = True
ACCOUNT_EMAIL_VERIFICATION = 'none'

# CSRF Settings - CRITICAL FOR PRODUCTION!
CSRF_TRUSTED_ORIGINS = [
    f'https://{RENDER_DOMAIN}',
    'https://*.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# Add your custom domain if you have one
if os.getenv('CUSTOM_DOMAIN'):
    CSRF_TRUSTED_ORIGINS.append(f'https://{os.getenv("CUSTOM_DOMAIN")}')

# Session and Cookie Security - CRITICAL FOR PRODUCTION!
# if not DEBUG:
#     SESSION_COOKIE_SECURE = True
#     CSRF_COOKIE_SECURE = True
#     SESSION_COOKIE_HTTPONLY = True
#     CSRF_COOKIE_HTTPONLY = True  # Set to False if you need JavaScript access to CSRF token
#     SESSION_COOKIE_SAMESITE = 'Lax'
#     CSRF_COOKIE_SAMESITE = 'Lax'
#     SECURE_SSL_REDIRECT = True
#     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#     SECURE_HSTS_SECONDS = 31536000  # 1 year
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True


# Replace your entire cookie security block (around line 54-67) with this:
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = False  # ← CHANGE THIS FROM True TO False
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Add these TWO lines right after that block:
# SESSION_COOKIE_DOMAIN = '.bynup.store'
# CSRF_COOKIE_DOMAIN = '.bynup.store'
    
#increase data upload limit
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024 #100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024 #100MB

#Stripe Keys
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# cryptomus keys
CRYPTOMUS_MERCHANT_ID = os.getenv('CRYPTOMUS_MERCHANT_ID')
CRYPTOMUS_PAYMENT_API_KEY = os.getenv('CRYPTOMUS_PAYMENT_API_KEY')
if DEBUG:
    CRYPTOMUS_TEST_MODE = True
else:
    CRYPTOMUS_TEST_MODE = False
    
from django.core.exceptions import ImproperlyConfigured
def get_env_variable(var_name):
    try:
        return os.environ[var_name]
    except KeyError:
        error_msg = f"Set the {var_name} environment variable"
        raise ImproperlyConfigured(error_msg)

ENCRYPTION_KEY = "cJlEDjup3IRVjHZhQlAtK6RYnLHAlFj6glG0BxlN41I"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party apps
    'channels',
    'django_user_agents',
    'geoip2',
    'cloudinary',
    'cloudinary_storage',
    'anymail',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    

    # my apps
    'analytics',
    'builder',
    'accounts',
    'payments',
    'drop_shipping',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', #For static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'builder.middleware.SubdomainMiddleware',  # Add this
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'builder.middleware.TrackProductViewMiddleware',
    'builder.middleware.SubdomainMiddleware',  # Add thi
    'middleware.fix_auth_middleware.FixAuthenticationMiddleware',
    'analytics.analytics_middleware.AnalyticsMiddleware', # Add this
    'accounts.middleware.AuthRedirectMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    

]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.auth_context',
                'builder.context_processors.website_auth_context',
                'builder.context_processors.recently_viewed_products',
                'builder.context_processors.domain_listing',  
                'builder.context_processors.branding_context',
                'builder.context_processors.subscription_tiers',
                'builder.context_processors.brand_context',
                'builder.context_processors.pending_domain_requests',


    
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'
# Channels configuration
ASGI_APPLICATION = 'src.asgi.application'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Channels layer - Use in-memory (NO REDIS)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# Celery - Run tasks synchronously (NO REDIS)
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_BROKER_URL = 'memory://'
CELERY_RESULT_BACKEND = 'cache+memory://'


# Remove the duplicate CACHES definition at the bottom of your file
# (Delete the second CACHES dictionary near the CJ API config)
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

# DATABASES = {
#     'default': dj_database_url.config(
#         default=DATABASE_URL,
#         conn_max_age=600,
#         conn_health_checks=True,
#     )
# }

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

else:
    DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS=[
    BASE_DIR/"static",
]

# Whitenoise for static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# MEDIA_URL='/media/'
# MEDIA_ROOT=BASE_DIR/'media'

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),  
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}


# Add authentication settings
AUTHENTICATION_BACKENDS = [
    'accounts.backends.MultiUserBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1


LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# settings.py additions
# CJ Dropshipping Configuration
CJ_API_CONFIG = {
    'BASE_URL': 'https://developers.cjdropshipping.com/api2.0/v1',
    'TOKEN_TTL': 14 * 24 * 3600,  # 14 days
    'MAX_DAILY_CALLS': 950,
    'MAX_CALLS_PER_MINUTE': 30,
    'REQUEST_TIMEOUT': 30,
    'RETRY_ATTEMPTS': 3,
}


# Logging Configuration
# In your settings.py, add or replace the LOGGING section:

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose'
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'cj_service': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

PRODUCTION_DOMAIN = 'bynup.store'
LOCAL_DOMAIN = 'http://127.0.0.1:8000/'
LOCAL_DOMAIN = 'http://127.0.0.1:8000/'
SITE_URL='https://bynup.store'
if DEBUG:
    # SITE_DOMAIN = 'http://127.0.0.1:8000/'
    SITE_DOMAIN = LOCAL_DOMAIN
else:
    SITE_DOMAIN = PRODUCTION_DOMAIN

MIDDLEWARE_DOMAIN_CUT = "bynup.store"



# Email settings for verification
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'bynupteam@gmail.com'
# EMAIL_HOST_PASSWORD = 'oler aslj jfcn wrmn'  # Use environment variable in production

ANYMAIL = {
    "RESEND_API_KEY": os.getenv("RESEND_API_KEY"),
}

# 3. Set the Backend
EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"

# 4. Identity Settings
# IMPORTANT: This must be a domain you verify in Resend (e.g., bynup.store)
DEFAULT_FROM_EMAIL = "Bynup <info@bynup.store>"
SERVER_EMAIL = "info@bynup.store"

# 5. Stability Settings
# Prevents a slow API from hanging your Gunicorn workers
EMAIL_TIMEOUT = 10


STOCK_SAFETY_BUFFER = 2  # Subtract this from CJ stock to prevent overselling

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
