# Generated by Django 5.1.4 on 2026-09-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_received_free_domain',
            field=models.BooleanField(default=False, help_text="Set to True when the user's first free domain is activated. Prevents double-claiming."),
        ),
    ]
